Feature/signin signup
WebNexia/learnscape-client pull request #5
Opened 2024-01-16 14:01 UTC by mbalci85

2024-01-16 14:23 UTC, mrselifbalci requested changes

2024-01-16 14:23 UTC, mrselifbalci commented on src/pages/Auth.tsx
> +			console.log(response.data);
Please remove this console.log

2024-01-16 14:34 UTC, mrselifbalci requested changes
You should add the .env file to .gitignore

2024-01-18 15:14 UTC, mbalci85 commented on src/pages/Auth.tsx
> +			console.log(response.data);
@mrselifbalci removed!

2024-01-18 15:16 UTC, mbalci85 commented
@mrselifbalci I have created enums, theme, and textfield generator component. Please revise new updates.

2024-01-18 15:22 UTC, mrselifbalci requested changes

2024-01-18 15:22 UTC, mrselifbalci commented on src/components/TextFieldGenerator.tsx
> +interface TextFieldGeneratorProps {
We should probably name this component something like StyledTextField or CustomTextField. Textfield generator sounds like a function name.

2024-01-18 15:28 UTC, mbalci85 commented on src/components/TextFieldGenerator.tsx
> +interface TextFieldGeneratorProps {
@mrselifbalci Oki doki ma'am

2024-01-18 15:31 UTC, mbalci85 commented on src/components/TextFieldGenerator.tsx
> +interface TextFieldGeneratorProps {
@mrselifbalci done

2024-01-18 15:43 UTC, mrselifbalci approved these changes

2024-01-18 15:45 UTC, merged